# Google YouTube Data API v3 token. You can get it from https://console.cloud.google.com/apis/credentials.
token = "Token"
# Default result count per request. Valid value is 0 to 50.
max_results = '10'
# Default region code
region_code ='KR'
# Default quality for download
quality = 'best'
# YouTube video url prefix except video id
youtube_url = 'https://youtube.com/watch?v='
# CORS URL
cors_url = '*'