# Google YouTube Data API v3 API key. You can get it from https://console.cloud.google.com/apis/credentials.
api_key = "Token"
# Default result count per request. Valid value is 0 to 50.
max_results = 10
# Default region code
region_code ='KR'
# Default quality for download
quality = 'best'
# CORS URL
cors_url = '*'